site_name: The CIO Wiki

theme:
  name: material
  custom_dir: overrides
  logo: assets/CIO.png
  favicon: assets/CIO.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/*
      base_path:
        - docs

nav:
  - Home: "index.md"
  # - About:
  # - Introduction: "pages/about/introduction.md"
  # - Thought Experiment: "pages/about/thought-experiment.md"
  # - Dependencies: "pages/about/dependencies.md"
  # - Objectives: "objectives.md"
  # - Concepts: "concepts.md"
  # - Repositories: "repositories.md"
  # - FAQ: "faq.md"
