site_name: CIO Wiki

theme:
  name: material
  custom_dir: overrides
  logo: assets/CIO.png
  favicon: assets/CIO.png
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking

markdown_extensions:
  - admonition
  - md_in_html

nav:
  - Home: "index.md"
  - About:
      - Introduction: "pages/introduction.md"
